Importing all the necessary libraries

In [1]:
import selenium
import pandas as pd
import time 

#importing selenium webdriver
from selenium import webdriver

#importing exceptions
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException,ElementNotInteractableException

#importing requests
import requests

#importing regex
import re

#importing warnings
import warnings
warnings.filterwarnings('ignore')

# 1. Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [2]:
#Accessing the Chrome Web Driver
driver=webdriver.Chrome('chromedriver.exe')
time.sleep(2)

In [3]:
#opening the url
url='https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)
time.sleep(2)

In [4]:
#maximizing the window
driver.maximize_window()
time.sleep(2)

In [5]:
#scraping names
names=[]
try:
    name_tag=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]")
    for i in name_tag:
        names.append(i.text)
        print(names)
except NoSuchElementException:
    name.append('No data')
except StaleElementReferenceException:
    name.append('No data')
    
    time.sleep(2)

['"Baby Shark Dance"[3]']
['"Baby Shark Dance"[3]', '"Despacito"[6]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]', '"Dame Tu Cosita"[31]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]', '"Dame Tu Cosita"[31]', '"Sugar"[32]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]', '"Dame Tu Cosita"[31]', '"Sugar"[32]', '"Roar"[33]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]', '"Dame Tu Cosita"[31]', '"Sugar"[32]', '"Roar"[33]', '"Counting Stars"[34]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]', '"Dame Tu Cosita"[31]', '"Sugar"[32]', '"Roar"[33]', '"Counting Stars"[34]', '"Sorry"[35]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]', '"Dame Tu Cosita"[31]', '"Sugar"[32]', '"Roar"[33]', '"Counting Stars"[34]', '"Sorry"[35]', '"Thinking Out Loud"[36]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]', '"Dame Tu Cosita"[31]', '"Sugar"[32]', '"Roar"[33]', '"Counting Stars"[34]', '"Sorry"[35]', '"Thinking Out Loud"[36]', '"Axel F"[37]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]', '"Dame Tu Cosita"[31]', '"Sugar"[32]', '"Roar"[33]', '"Counting Stars"[34]', '"Sorry"[35]', '"Thinking Out Loud"[36]', '"Axel F"[37]', '"Girls Like You"[38]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]', '"Dame Tu Cosita"[31]', '"Sugar"[32]', '"Roar"[33]', '"Counting Stars"[34]', '"Sorry"[35]', '"Thinking Out Loud"[36]', '"Axel F"[37]', '"Girls Like You"[38]', '"Faded"[39]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]', '"Dame Tu Cosita"[31]', '"Sugar"[32]', '"Roar"[33]', '"Counting Stars"[34]', '"Sorry"[35]', '"Thinking Out Loud"[36]', '"Axel F"[37]', '"Girls Like You"[38]', '"Faded"[39]', '"Dark Horse"[40]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]', '"Dame Tu Cosita"[31]', '"Sugar"[32]', '"Roar"[33]', '"Counting Stars"[34]', '"Sorry"[35]', '"Thinking Out Loud"[36]', '"Axel F"[37]', '"Girls Like You"[38]', '"Faded"[39]', '"Dark Horse"[40]', '"Let Her Go"[41]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]', '"Dame Tu Cosita"[31]', '"Sugar"[32]', '"Roar"[33]', '"Counting Stars"[34]', '"Sorry"[35]', '"Thinking Out Loud"[36]', '"Axel F"[37]', '"Girls Like You"[38]', '"Faded"[39]', '"Dark Horse"[40]', '"Let Her Go"[41]', '"Baa Baa Black Sheep"[42]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]', '"Dame Tu Cosita"[31]', '"Sugar"[32]', '"Roar"[33]', '"Counting Stars"[34]', '"Sorry"[35]', '"Thinking Out Loud"[36]', '"Axel F"[37]', '"Girls Like You"[38]', '"Faded"[39]', '"Dark Horse"[40]', '"Let Her Go"[41]', '"Baa Baa Black Sheep"[42]', '"Bailando"[43]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]', '"Dame Tu Cosita"[31]', '"Sugar"[32]', '"Roar"[33]', '"Counting Stars"[34]', '"Sorry"[35]', '"Thinking Out Loud"[36]', '"Axel F"[37]', '"Girls Like You"[38]', '"Faded"[39]', '"Dark Horse"[40]', '"Let Her Go"[41]', '"Baa Baa Black Sheep"[42]', '"Bailando"[43]', '"Lean On"[44]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]', '"Dame Tu Cosita"[31]', '"Sugar"[32]', '"Roar"[33]', '"Counting Stars"[34]', '"Sorry"[35]', '"Thinking Out Loud"[36]', '"Axel F"[37]', '"Girls Like You"[38]', '"Faded"[39]', '"Dark Horse"[40]', '"Let Her Go"[41]', '"Baa Baa Black Sheep"[42]', '"Bailando"[43]', '"Lean On"[44]', '"Shake It Off"[45]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]', '"Dame Tu Cosita"[31]', '"Sugar"[32]', '"Roar"[33]', '"Counting Stars"[34]', '"Sorry"[35]', '"Thinking Out Loud"[36]', '"Axel F"[37]', '"Girls Like You"[38]', '"Faded"[39]', '"Dark Horse"[40]', '"Let Her Go"[41]', '"Baa Baa Black Sheep"[42]', '"Bailando"[43]', '"Lean On"[44]', '"Shake It Off"[45]', '"Perfect"[46]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]', '"Dame Tu Cosita"[31]', '"Sugar"[32]', '"Roar"[33]', '"Counting Stars"[34]', '"Sorry"[35]', '"Thinking Out Loud"[36]', '"Axel F"[37]', '"Girls Like You"[38]', '"Faded"[39]', '"Dark Horse"[40]', '"Let Her Go"[41]', '"Baa Baa Black Sheep"[42]', '"Bailando"[43]', '"Lean On"[44]', '"Shake It Off"[45]', '"Perfect"[46]', '"Waka Waka (This Time for Africa)"[47]']
['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Phonics Song with Two Words"[21]', '"Learning Colors – Colorful Eggs on a Farm"[22]', '"Uptown Funk"[23]', '"Masha and the Bear – Recipe for Disaster"[24]', '"Gangnam Style"[25]', '"Wheels on the Bus"[30]', '"Dame Tu Cosita"[31]', '"Sugar"[32]', '"Roar"[33]', '"Counting Stars"[34]', '"Sorry"[35]', '"Thinking Out Loud"[36]', '"Axel F"[37]', '"Girls Like You"[38]', '"Faded"[39]', '"Dark Horse"[40]', '"Let Her Go"[41]', '"Baa Baa Black Sheep"[42]', '"Bailando"[43]', '"Lean On"[44]', '"Shake It Off"[45]', '"Perfect"[46]', '"Waka Waka (This Time for Africa)"[47]', '"Mi Gente"[48]']

In [6]:
#scraping rank
rank=[]
try:
    rank_tag=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]")
    for i in rank_tag:
        rank.append(i.text)
except NoSuchElementException:
    name.append('No data')
except StaleElementReferenceException:
    name.append('No data')
    
print(rank)

['1.', '2.', '3.', '4.', '5.', '6.', '7.', '8.', '9.', '10.', '11.', '12.', '13.', '14.', '15.', '16.', '17.', '18.', '19.', '20.', '21.', '22.', '23.', '24.', '25.', '26.', '27.', '28.', '29.', '30.']

In [7]:
#scraping artist
artist=[]
try:
    artist_tag=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for i in artist_tag:
        artist.append(i.text)
except NoSuchElementException:
    name.append('No data')
except StaleElementReferenceException:
    name.append('No data')

print(artist)

["Pinkfong Baby Shark - Kids' Songs & Stories", 'Luis Fonsi', 'LooLoo Kids', 'Ed Sheeran', 'Wiz Khalifa', 'Cocomelon – Nursery Rhymes', 'ChuChu TV', 'Miroshka TV', 'Mark Ronson', 'Get Movies', 'Psy', 'Cocomelon – Nursery Rhymes', 'El Chombo', 'Maroon 5', 'Katy Perry', 'OneRepublic', 'Justin Bieber', 'Ed Sheeran', 'Crazy Frog', 'Maroon 5', 'Alan Walker', 'Katy Perry', 'Passenger', 'Cocomelon – Nursery Rhymes', 'Enrique Iglesias', 'Major Lazer', 'Taylor Swift', 'Ed Sheeran', 'Shakira', 'J Balvin']

In [8]:
#scraping views
views=[]
try:
    views_tag=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for i in views_tag:
        views.append(i.text)
except NoSuchElementException:
    name.append('No data')
except StaleElementReferenceException:
    name.append('No data')
    
print(views)

['10.53', '7.82', '6.31', '5.69', '5.48', '5.27', '4.58', '4.56', '4.54', '4.49', '4.40', '3.96', '3.92', '3.68', '3.56', '3.56', '3.54', '3.44', '3.32', '3.28', '3.27', '3.26', '3.21', '3.21', '3.19', '3.19', '3.16', '3.14', '3.12', '3.07']

In [9]:
#scraping upload date
upload_date=[]
try:
    upload_date_tag=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for i in upload_date_tag:
        upload_date.append(i.text)
except NoSuchElementException:
    name.append('No data')
except StaleElementReferenceException:
    name.append('No data')
    
print(upload_date)

['June 17, 2016', 'January 12, 2017', 'October 8, 2016', 'January 30, 2017', 'April 6, 2015', 'May 2, 2018', 'March 6, 2014', 'February 27, 2018', 'November 19, 2014', 'January 31, 2012', 'July 15, 2012', 'May 24, 2018', 'April 5, 2018', 'January 14, 2015', 'September 5, 2013', 'May 31, 2013', 'October 22, 2015', 'October 7, 2014', 'June 16, 2009', 'May 31, 2018', 'December 3, 2015', 'February 20, 2014', 'July 25, 2012', 'June 25, 2018', 'April 11, 2014', 'March 22, 2015', 'August 18, 2014', 'November 9, 2017', 'June 4, 2010', 'June 29, 2017']

In [10]:
len(rank),len(names),len(artist),len(upload_date),len(views)

(30, 30, 30, 30, 30)

In [11]:
#making the dataframe
df=pd.DataFrame({'Rank':rank,'Name':names,'Artist':artist,'Upload Date':upload_date,'Views(billion)':views})
df

,Rank,Name,Artist,Upload Date,Views(billion)
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.53
1,2.,"""Despacito""[6]",Luis Fonsi,"January 12, 2017",7.82
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,"October 8, 2016",6.31
3,4.,"""Shape of You""[13]",Ed Sheeran,"January 30, 2017",5.69
4,5.,"""See You Again""[15]",Wiz Khalifa,"April 6, 2015",5.48
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.27
6,7.,"""Phonics Song with Two Words""[21]",ChuChu TV,"March 6, 2014",4.58
7,8.,"""Learning Colors – Colorful Eggs on a Farm""[22]",Miroshka TV,"February 27, 2018",4.56
8,9.,"""Uptown Funk""[23]",Mark Ronson,"November 19, 2014",4.54
9,10.,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,"January 31, 2012",4.49
10,11.,"""Gangnam Style""[25]",Psy,"July 15, 2012",4.40
11,12.,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,"May 24, 2018",3.96
12,13.,"""Dame Tu Cosita""[31]",El Chombo,"April 5, 2018",3.92
13,14.,"""Sugar""[32]",Maroon 5,"January 14, 2015",3.68
14,15.,"""Roar""[33]",Katy Perry,"September 5, 2013",3.56
15,16.,"""Counting Stars""[34]",OneRepublic,"May 31, 2013",3.56
16,17.,"""Sorry""[35]",Justin Bieber,"October 22, 2015",3.54
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,"October 7, 2014",3.44
18,19.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.32
19,20.,"""Girls Like You""[38]",Maroon 5,"May 31, 2018",3.28
20,21.,"""Faded""[39]",Alan Walker,"December 3, 2015",3.27
21,22.,"""Dark Horse""[40]",Katy Perry,"February 20, 2014",3.26
22,23.,"""Let Her Go""[41]",Passenger,"July 25, 2012",3.21
23,24.,"""Baa Baa Black Sheep""[42]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.21
24,25.,"""Bailando""[43]",Enrique Iglesias,"April 11, 2014",3.19
25,26.,"""Lean On""[44]",Major Lazer,"March 22, 2015",3.19
26,27.,"""Shake It Off""[45]",Taylor Swift,"August 18, 2014",3.16
27,28.,"""Perfect""[46]",Ed Sheeran,"November 9, 2017",3.14
28,29.,"""Waka Waka (This Time for Africa)""[47]",Shakira,"June 4, 2010",3.12
29,30.,"""Mi Gente""[48]",J Balvin,"June 29, 2017",3.07

# 2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1
st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [12]:
#Accessing the Chrome Web Driver
driver=webdriver.Chrome('chromedriver.exe')
time.sleep(2)

In [13]:
#opening the url
url='https://www.bcci.tv/'
driver.get(url)
time.sleep(2)

In [14]:
#maximizing the window
driver.maximize_window()
time.sleep(2)

In [15]:
#chooseing international fixture
int_fix_tag=driver.find_element_by_xpath('/html/body/nav/div/div[2]/ul[1]/li[2]/a')
try:
    int_fix_tag.click()
except ElementNotInteractableException:
    driver.int_fix_tag.get_attribute('href')

In [17]:
#Scraping match title i.e. first title
title=[]

title_tag=driver.find_elements_by_xpath('//span[@class="matchOrderText ng-binding ng-scope"]')
for i in title_tag:
    title.append(i.text)
print(title)

['1st T20I -', '2nd T20I -', '3rd T20I -', '4th T20I -', '5th T20I -']

In [18]:
#Scraping series
series=[]

series_tag=driver.find_elements_by_xpath('//div[@class="fixture-card-top"]')
for i in series_tag:
    series.append(i.text.split()[0:5])
print(series)

[['SOUTH', 'AFRICA', 'TOUR', 'OF', 'INDIA'], ['SOUTH', 'AFRICA', 'TOUR', 'OF', 'INDIA'], ['SOUTH', 'AFRICA', 'TOUR', 'OF', 'INDIA'], ['SOUTH', 'AFRICA', 'TOUR', 'OF', 'INDIA'], ['SOUTH', 'AFRICA', 'TOUR', 'OF', 'INDIA']]

In [19]:
#scraping place
place=[]

place_tag=driver.find_elements_by_xpath('//span[@class="ng-binding ng-scope"]')
for i in place_tag:
    place.append(i.text)
print(place)

['Arun Jaitley Stadium,', 'Barabati Stadium,', 'Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium,', 'Saurashtra Cricket Association Stadium,', 'M Chinnaswamy Stadium,']

In [20]:
#scraping date
date=[]

date_tag=driver.find_elements_by_xpath('//div[@class="match-card-left match-schedule"]')
for i in date_tag:
    date.append(i.text)
print(date)

['9 JUN 2022', '12 JUN 2022', '14 JUN 2022', '17 JUN 2022', '19 JUN 2022']

In [21]:
#scraping time
match_time=[]

time_tag=driver.find_elements_by_xpath('//h5[@class="text-right ng-binding"]')
for i in time_tag:
    match_time.append(i.text)
print(match_time)

['7:30 PM IST', '7:30 PM IST', '7:30 PM IST', '7:30 PM IST', '7:30 PM IST']

In [22]:
len(title),len(series),len(place),len(date),len(match_time)

(5, 5, 5, 5, 5)

In [23]:
#preparing the dataframe
df=pd.DataFrame({"Match Title":title,
                "Series":series,
                "Place":place,
                "Date":date,
                "Time":time})
df

,Match Title,Series,Place,Date,Time
0,1st T20I -,"[SOUTH, AFRICA, TOUR, OF, INDIA]","Arun Jaitley Stadium,",9 JUN 2022,<module 'time' (built-in)>
1,2nd T20I -,"[SOUTH, AFRICA, TOUR, OF, INDIA]","Barabati Stadium,",12 JUN 2022,<module 'time' (built-in)>
2,3rd T20I -,"[SOUTH, AFRICA, TOUR, OF, INDIA]","Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium,",14 JUN 2022,<module 'time' (built-in)>
3,4th T20I -,"[SOUTH, AFRICA, TOUR, OF, INDIA]","Saurashtra Cricket Association Stadium,",17 JUN 2022,<module 'time' (built-in)>
4,5th T20I -,"[SOUTH, AFRICA, TOUR, OF, INDIA]","M Chinnaswamy Stadium,",19 JUN 2022,<module 'time' (built-in)>

# 3. Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [24]:
#Accessing the Chrome Web Driver
driver=webdriver.Chrome('chromedriver.exe')
time.sleep(3)

#opening the url
url='https://www.guru99.com/'
driver.get(url)
time.sleep(1)

#maximizing the window
driver.maximize_window()
time.sleep(2)

#Clicking on selenium under testing
try:
    selenium=driver.find_element_by_xpath('//*[@id="java_technologies"]/li[3]/a')
    selenium.click()
except ElementNotInteractableException:
    driver.get(selenium.get_attribute('href'))
    time.sleep(2)

#Clicking on Selenium Exception Handling(common exception list) under Advanced Webdriver Stuff
try:
    exceptions=driver.find_element_by_xpath('//*[@id="post-193"]/div/div/table[5]/tbody/tr[34]/td[1]/a')
    exceptions.click()
except ElementNotInteractableException:
    driver.get(exception.get_attribute('href'))
    time.sleep(2)

#scraping the common exception
exception_name=[]
try:
    exception_tag=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]")
    for i in exception_tag[1:]:
        exception_name.append(i.text)
except NoSuchElementException:               #handling no such element exception
    name.append('No details available')
time.sleep(2)   

#scraping exceptions description
desc=[]
try:
    desc_tag=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]")
    for i in desc_tag[1:]:
        desc.append(i.text)
except NoSuchElementException:#handling no such element exception
    desc.append('No details available')
time.sleep(2)

#creating dataframe
df=pd.DataFrame({"Exception_name":exception_name,"Description of Exception":desc})
df

,Exception_name,Description of Exception
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

# 4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP(18-19)
D) GSDP(17-18)
E) Share(2017)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [32]:
# Accessing the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the url
url = "http://statisticstimes.com/"
driver.get(url)
time.sleep(2)

#maximizing the window
driver.maximize_window()
time.sleep(2)

#clicking on economy button
economy=driver.find_element_by_xpath('//*[@id="top"]/div[2]/div[2]/button')
try:
    economy.click()
except ElementNotInteractableException:
    driver.get(economy.get_attribute('href'))
time.sleep(2)

#going to india link
driver.get('https://www.statisticstimes.com/economy/india-statistics.php')

#clicking on gdp of indian states

try:
    indian_states=driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
    indian_states.click()
except ElementNotInteractableException:
    driver.get(indian_states.get_attribute('href="economy/india-statistics.php')) 
time.sleep(2)


#scraping rank
ranks=[]
try:
    rank_tag=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[1]")
    for i in rank_tag:
        ranks.append(i.text)
except NoSuchElementException:                 #handling no such element exception
    ranks.append('No details available')
time.sleep(2)

#scraping States
State=[]
try:
    state_tag=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[2]")
    for i in state_tag:
        State.append(i.text)
except NoSuchElementException:                 #handling no such element exception
    State.append('No details available')
time.sleep(2)


#scraping GSDP(19-20)
GSDP_20=[]
try:
    GSDP_20_tag=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[3]")
    for i in GSDP_20_tag:
        GSDP_20.append(i.text)
except NoSuchElementException:           #handling no such element exception
    GSDP_20.append('No details available')
time.sleep(2)    
    
#scraping GSDP(18-19)
GSDP_19=[]
try:
    GSDP_19_tag=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[4]")
    for i in GSDP_19_tag:
        GSDP_19.append(i.text)
except NoSuchElementException:        #handling no such element exception
    GSDP_19.append('No details available')
time.sleep(2)

#scraping share (18-19)
share=[]
try:
    share_tag=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[5]")
    for i in share_tag:
        share.append(i.text)
except NoSuchElementException:          #handling no such element exception
    share.append('No details available')
time.sleep(2)

#scraping GDP(billion$)
GDP_billion=[]
try:
    GDP_billion_tag=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[6]")
    for i in GDP_billion_tag:
        GDP_billion.append(i.text)
except NoSuchElementException:            #handling no such element exception
    GDP_billion.append('No details available')
time.sleep(2)

#creating dataframe
df=pd.DataFrame({'Rank':ranks,'State':State,'GSDP(19-20)':GSDP_20,'GSDP(18-19)':GSDP_19,'Share(18-19)':share,'GDP(Billion_$)':GDP_billion})
df

,Rank,State,GSDP(19-20),GSDP(18-19),Share(18-19),GDP(Billion_$)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# 5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [33]:
# Accessing the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)


# Opening the github
url = "https://github.com/"
driver.get(url)
time.sleep(2)

#maximizing the window
driver.maximize_window()
time.sleep(2)

# clicking on option button
explore=driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary')
explore.click()
time.sleep(2)

#finding trending option
explore=driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a')
try:
    explore.click()
except:
    driver.get(explore.get_attribute('href'))
time.sleep(2)


# making empty lists    
repo_urls=[]
Contributors_count=[]
Language_used=[]
repo_title=[]
repo_desc=[]

#scraping repositories urls

repos=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")
for i in repos:
    repo_urls.append(i.get_attribute('href'))
time.sleep(2) 

#scraping repositories title
repo_title=[]
try:
    repos=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']")
    for i in repos:
        repo_title.append(i.text)
except NoSuchElementException:#handling no such element exception
    repo_title.append('No details available')
time.sleep(3)
    

for i in repo_urls:
    driver.get(i)
    l=[]
    time.sleep(3)
    #scraping repositories discription
    try:
        repo = driver.find_element_by_xpath("/html/body/div[4]/div/main/div[2]/div/div/div[2]/div[2]/div/div[1]/div/p")
        repo_desc.append(repo.text)
    except NoSuchElementException:
        repo_desc.append('-')
    
    #scraping contributors count
    try:
        count=driver.find_element_by_xpath("//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        Contributors_count.append(count.text)
    except NoSuchElementException:#handling no such element exception
        Contributors_count.append('No details available')
    time.sleep(2)
    
     #scraping languages used   
    languages=driver.find_elements_by_xpath("//li[@class='d-inline']//a//span[1]")
    if languages:    
        for i in languages:
            l.append(i.text)
    else:
        l.append('No languages used')
    Language_used.append(l)   
    
time.sleep(2)   

#creating dataframe
df=pd.DataFrame({'Title':repo_title,
                'Description':repo_desc,
                'Contributors_count':Contributors_count,
                'Language_used':Language_used})
df

,Title,Description,Contributors_count,Language_used
0,freeCodeCamp / freeCodeCamp,-,"4,430","[TypeScript, JavaScript, CSS, Shell, Dockerfil..."
1,SebLague / Geographical-Adventures,-,2,"[C#, ShaderLab, HLSL, GLSL]"
2,pyscript / pyscript,-,32,"[JavaScript, HTML, TypeScript, Python, Svelte,..."
3,programthink / zhao,-,2,[Python]
4,microsoft / ML-For-Beginners,-,111,"[Jupyter Notebook, Python, HTML, Vue, JavaScri..."
5,twbs / bootstrap,-,"1,295","[JavaScript, HTML, SCSS, CSS, PowerShell]"
6,mvt-project / mvt,-,32,[Python]
7,twostraws / simple-swiftui,-,3,[Swift]
8,programthink / books,-,No details available,[No languages used]
9,justjavac / free-programming-books-zh_CN,-,114,[No languages used]
10,Wechat-ggGitHub / Awesome-GitHub-Repo,-,No details available,[No languages used]
11,dataabc / weiboSpider,-,14,[Python]
12,papers-we-love / papers-we-love,-,253,[Shell]
13,Grasscutters / Grasscutter,-,25,[Java]
14,ipfs / go-ipfs,-,327,"[Go, Shell, HTML, Makefile, Dockerfile, CSS]"
15,PacktPublishing / The-Kaggle-Book,-,4,[Jupyter Notebook]
16,replicate / cog,-,15,"[Go, Python]"
17,appsmithorg / appsmith,-,189,"[TypeScript, Java, JavaScript, Shell, HTML, Ha..."
18,pyodide / pyodide,-,123,"[Python, C, TypeScript, JavaScript, Makefile, ..."
19,ItsKaitlyn03 / OculusKiller,-,No details available,[C#]
20,directus / directus,-,244,"[TypeScript, Vue, SCSS, JavaScript, CSS, Liquid]"
21,scottbez1 / smartknob,-,2,"[C++, C, Python, Shell]"
22,palantir / blueprint,-,306,"[TypeScript, SCSS, JavaScript]"
23,Runc2333 / dingdong-helper-node,-,No details available,[JavaScript]
24,dotnet / docs,-,"2,090",[No languages used]

# 6. Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [34]:
# Accessing the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Getting Url
url = "https://www.billboard.com/"
driver.get(url)
time.sleep(2)

#maximizing the window
driver.maximize_window()
time.sleep(2)

#clicking the hot 100 songs link
charts=driver.find_element_by_xpath('//*[@id="main-wrapper"]/header/div[2]/div/nav/ul/li[1]/a')
try:
    charts.click()
except ElementNotInteractableException:
    driver.get(charts.get_attribute('href'))
time.sleep(2)


#scraping song names
song_name=[]
try:
    names=driver.find_elements_by_xpath("//span[@class='chart-element__information']/span[@class='chart-element__information__song text--truncate color--primary']")
except NoSuchElementException:       #handling no such element exception
    song_name.append('No details available')
time.sleep(2)    


#scraping artist_names 
artist_name=[]
try:
    names=driver.find_elements_by_xpath("//span[@class='chart-element__information']/span[@class='chart-element__information__artist text--truncate color--secondary']")
    for i in names:
        artist_name.append(i.text)
except NoSuchElementException:        #handling no such element exception
    artist_name.append('No details available')
time.sleep(2)

#scraping last week rank
last_week_rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--last']")
    for i in ranks:
        last_week_rank.append(i.text)
except NoSuchElementException:        #handling no such element exception
    last_week_rank.append('No details available') 
time.sleep(2)

#scraping peak rank
peak_rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--peak']")
    for i in ranks:
        peak_rank.append(i.text)
except NoSuchElementException:      #handling no such element exception
    peak_rank.append('No details available')
time.sleep(2)

#scraping weeks on chart
weeks=[]
try:
    week_count=driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--week']")
    for i in week_count:
        weeks.append(i.text)
except NoSuchElementException:          #handling no such element exception
    weeks.append('No details available')
time.sleep(2)


#creating dataframe
df=pd.DataFrame({'Song_Name':song_name,
                'Artist_Name':artist_name,
                'Last_week_rank':last_week_rank,
                'Peak':peak_rank,
                'Weeks_on_chart':weeks})
df

Empty DataFrame
Columns: [Song_Name, Artist_Name, Last_week_rank, Peak, Weeks_on_chart]
Index: []

# 7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [35]:
from bs4 import BeautifulSoup

# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the naukri.com
url = 'https://www.naukri.com/browse-jobs'
driver.get(url)
time.sleep(2)

#maximizing the window
driver.maximize_window()
time.sleep(2)

#clicking on recruiters link
driver.get('https://www.naukri.com/hr-recruiters-consultants')
time.sleep(1)

#accesing search bar
search=driver.find_element_by_xpath('//*[@id="skill"]/div[1]/div[2]/input')
search.send_keys("Data Science")
time.sleep(1)

#clicking on search button
button=driver.find_element_by_xpath("//button[@id='qsbFormBtn']")
button.click()
time.sleep(1)

#scrapping names
name=[]
try:
    names=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[1]")
    for i in names:
        name.append(i.text)
except NoSuchElementException:           #handling no such element exception
    name.append('No details available')
time.sleep(2)

#scrapping designation
designation=[]
try:
    designation_list=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/span[1]")
    for i in designation_list:
        designation.append(i.text)
except NoSuchElementException:        #handling no such element exception
    designation.append('No details available')
time.sleep(2)


#scrapping company names
company=[]
try:
    companies=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[2]")
    for i in companies:
        company.append(i.text)
except NoSuchElementException:#handling no such element exception
    company.append('No details available')
time.sleep(2)

#scrapping location names
location=[]
soup=BeautifulSoup(driver.page_source,'html.parser')
l=soup.find_all('div',attrs={'vcard'})
for i in l:
    try:
        location.append(i.find('small').text)
    except AttributeError :
        location.append("No details available")
time.sleep(2)

#skills they hire for
skill=[]
try:
    skills=driver.find_elements_by_xpath("//div[@class='recInfo']/div[2]")
    for i in skills:
        skill.append(i.text)
except NoSuchElementException:        #handling no such element exception
    skill.append('No details available')
time.sleep(2)    

#creating dataframe
df=pd.DataFrame({'Name':name,'Designation':designation,'Company':company,"Location":location,'Skills I hire':skill})
df

,Name,Designation,Company,Location,Skills I hire
0,Aakash Harit,HR Manager,Data Science Network,Delhi,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,Hyderabad / Secunderabad,".Net, Java, Data Science, Linux Administration..."
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Pune,"Data Science, Artificial Intelligence, Machine..."
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,Ahmedabad,"Mean Stack, javascript, angularjs, mongodb, We..."
4,subhas patel,Founder CEO,LibraryXProject,UK - (london),"Hadoop, Spark, Digital Strategy, Data Architec..."
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Vadodara / Baroda,"Analytics, Business Intelligence, Business Ana..."
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Chennai,Data Science
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Trivandrum,"Machine Learning, algorithms, Go Getter, Compu..."
8,Asif Lucknowi,Director,Weupskill- Live Wire India,Indore,"Technical Training, Software Development, Pres..."
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,Bengaluru / Bangalore,"Software Development, It Sales, Account Manage..."
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions,Hyderabad,"Oracle Dba, Data Science, Data Warehousing, ET..."
11,Kalpana Dumpala,Executive Hiring,Innominds Software,Hyderabad / Secunderabad,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
12,Mubarak,Company HR,MoneyTap,Bengaluru / Bangalore,"Business Intelligence, Data Warehousing, Data ..."
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,Mumbai,"Office Administration, Hr Administration, tele..."
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Hyderabad / Secunderabad,"Social Media, digital media maketing, seo, smm..."
15,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,Chandigarh,"React.js, Data Science, Java, Front End, Busin..."
16,Kapil Devang,HR Manager,BISP Solutions,Bhopal,"Big Data, Hadoop, Data Analytics, Data Science"
17,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Pune,"Qlikview, Qlik Sense, Microsoft Azure, Power B..."
18,Manisha Yadav,HR Executive,Easi Tax,Navi Mumbai,"Telecalling, Client Interaction, Marketing, Re..."
19,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Cochin,Data Science
20,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Delhi,"Corporate Sales, Software Development, Softwar..."
21,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,Hyderabad / Secunderabad,"Data Analytics, Data Science, Machine Learning..."
22,Rithika dadwal,HR Recruiter,Affine Analytics,Pune,"Data Science, Machine Learning, Python, R, Dee..."
23,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Pune,"Big Data, Data Science, Artificial Intelligenc..."
24,Shaun Rao,Manager Human Resources,Exela Technologies,Pune,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Pune,"Data Science, Artificial Intelligence, Machine..."
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,Bengaluru / Bangalore,"Software Architecture, Vp Engineering, Product..."
27,kumar,Proprietor,trainin,Bengaluru / Bangalore,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,No details available,"Signal Processing, Machine Learning, Neural Ne..."
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Delhi,"Web Technologies, Project Management, Software..."
30,Dhruv Dev Dubey,Company Recruitment Head,Confidential,Bengaluru / Bangalore,"Server Administartion, Verilog, Vhdl, Digital ..."
31,Avodha,Business Development Associate,Nikitha Palaparthi,Hyderabad / Secunderabad,"Ethical Hacking, Security Operations Center, S..."
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Mysoru / Mysore,"Data Analytics, Managed Services, Team Leading..."
33,Ravi Dubey,Recruitment Manager,HyrEzy Talent Solutions LLP,Ghaziabad,Walmart Interra Skeps Expressstores indifi whi...
34,Priya Khare,Senior Manager,Independent Consultant,Bengaluru / Bangalore,"Data Science, Artificial Intelligence, analyti..."
35,Amit Sharma,Consultant,ASCO consulting,New Delhi,"Machine Learning, Artificial Intelligence, Dat..."
36,Kanan,senior technology instructor,NY INST,Chennai,"C, C++, Artificial Intelligence, Python, Php, ..."
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Aligarh,"Relationship Management, Retail Sales, Private..."
38,Brad,"Manager, Technical Recruiting",O.C. Tanner,Salt Lake City,"Data Science, Software Engineering"
39,Rutuja Pawar,Technical Recruiter,Demand Matrix,Pune,"Data Science, Big Data Analytics, Digital Mark..."
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Bengaluru / Bangalore,"Data Science, Recruitment, Salary"
41,Ankit Sinha,Head Analytics,Suntech Global,Mumbai,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Indore,"Software Development, Business Intelligence, B..."
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Bengaluru / Bangalore,"Data Science, Node.js, Angularjs"
44,Ashwini,Director Global Delivery,MRP Advisers,MYSORE,"Data Science, Media Marketing, Resource Planni..."
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Hyderabad / Secunderabad,"Data Analysis, Learning, Data Science, Compute..."
46,Rajani Nagaraj,HR Manager,WildJasmine,Bengaluru / Bangalore,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
47,ROHIT Kumar,Architect,LNT Private Limited,Mumbai,"Software Development, Core Java, Unit Testing,..."
48,Amir Chowdhury,Managing Partner,Granular.ai,No details available,"Machine Learning, Data Science, Product Manage..."
49,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,Hyderabad / Secunderabad,"Data Science, Machine Learning, Big Data Analy..."

# 8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [36]:
# Accessing the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the url 'theguardian.com'
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver.get(url)
time.sleep(2)

#scraping the names book
book_name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[2]")
    for i in names:
        book_name.append(i.text)
except NoSuchElementException:              #handling no such element exception
    book_name.append('No details available')
time.sleep(2)

#scraping the author names
author_name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")
    for i in names:
        author_name.append(i.text)
except NoSuchElementException:#handling no such element exception
    author_name.append('No details available')
time.sleep(2)


#scraping Sale
Sale=[]
try:
    sale=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")
    for i in sale:
        Sale.append(i.text)
except NoSuchElementException:#handling no such element exception
    Sale.append('No details available')
time.sleep(2)    

#scraping publisher
publisher=[]
try:
    publishers=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
    for i in publishers:
        publisher.append(i.text)
except NoSuchElementException:#handling no such element exception
    publisher.append('No details available')
time.sleep(2)

#scraping genre
genre=[]
try:
    genres=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('No details available')
time.sleep(2)

#creating dataframe
df=pd.DataFrame({"Book_name":book_name,"Author_name":author_name,'Volume sold':Sale,'Publisher':publisher,'Genre':genre})
df

,Book_name,Author_name,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# 9. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [37]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the imdb.com
url = "https://www.imdb.com/list/ls095964455"
driver.get(url)
time.sleep(2)

# scraping name of webseries
name=[]
try:
    names=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
    for i in names:
        name.append(i.text)
except NosuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)


# scraping year of release
years=[]
try:
    span=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
    for i in span:
        years.append(i.text)
except NosuchElementException:#handling no such element exception
    years.append('No details available')
time.sleep(2)


# scraping genre
genre=[]
try:
    genres=driver.find_elements_by_xpath("//span[@class='genre']")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('No details available')
time.sleep(2)

# scraping run_time
run_time=[]
try:
    info=driver.find_elements_by_xpath("//span[@class='runtime']")
    for i in info:
        run_time.append(i.text)
except NoSuchElementException:#handling no such element exception
    run_time.append('No details available')
time.sleep(2)


# scraping rating
rating=[]
try:
    info=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
    for i in info:
        rating.append(i.text)
except NoSuchElementException:#handling no such element exception
    rating.append('No details available')
time.sleep(2)

# scraping votes
votes=[]
try:
    info=driver.find_elements_by_xpath("//span[@name='nv']")
    for i in info:
        votes.append(i.text)
except NoSuchElementException:#handling no such element exception
    votes.append('No details available')
time.sleep(2)


#creating dataframe
df=pd.DataFrame({"Name":name,"years":years,"Genre":genre,"Run_time":run_time,"Rating":rating,"Votes":votes})
df

,Name,years,Genre,Run_time,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,981,128"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"986,827"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"944,131"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"282,069"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"241,970"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.4,"48,553"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"59,189"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"188,870"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"40,023"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"226,417"

# 10. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code.

In [38]:
# Accessing the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the url imdb.com
url = "https://archive.ics.uci.edu/"
driver.get(url)
time.sleep(2)

#clicking show all datasets link
show=driver.find_element_by_xpath("//a[@href='datasets.php']")
show.click()
time.sleep(1)


#scraping dataset names
name=[]
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)

#scraping data type
data_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in info[1:]:
         data_type.append(i.text)
except NoSuchElementException:
    data_type.append("No information")
time.sleep(2)


#scraping dataset names
default_task=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in info[1:]:
         default_task.append(i.text)
except NoSuchElementException:
    default_task.append("No information")
time.sleep(2)

#scraping dataset names
attr_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in info[1:]:
         attr_type.append(i.text)
except NoSuchElementException:
    attr_type.append("No information")
time.sleep(2)


#scraping dataset names
no_of_instances=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in info[1:]:
         no_of_instances.append(i.text)
except NoSuchElementException:
    no_of_instances.append("No information")
time.sleep(2)


#scraping dataset names
no_of_attributes=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in info[1:]:
         no_of_attributes.append(i.text)
except NoSuchElementException:
    no_of_attributes.append("No information")
time.sleep(2)


#scraping dataset names
year=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in info[1:]:
         year.append(i.text)
except NoSuchElementException:
    year.append("No information")
time.sleep(2)

#creating dataframe
df=pd.DataFrame({'Name':name,'Data_type':data_type,'Task':default_task,'Attribute_type':attr_type,'No_of_instances':no_of_instances,'No_of_attributes':no_of_attributes,'Year':year})
df

,Name,Data_type,Task,Attribute_type,No_of_instances,No_of_attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021